call ZIP_DLCS_HELPER.bat dlc\dlc001_german_historical_portraits\ dlc001
call ZIP_DLCS_HELPER.bat dlc\dlc002_polish_content_pack\ dlc002
call ZIP_DLCS_HELPER.bat dlc\dlc003_rocket_launcher_unit_pack\ dlc003
call ZIP_DLCS_HELPER.bat dlc\dlc004_famous_battleships_unit_pack\ dlc004
call ZIP_DLCS_HELPER.bat dlc\dlc005_heavy_cruisers_unit_pack\ dlc005
call ZIP_DLCS_HELPER.bat dlc\dlc006_soviet_tanks_unit_pack\ dlc006
call ZIP_DLCS_HELPER.bat dlc\dlc007_german_tanks_unit_pack\ dlc007
call ZIP_DLCS_HELPER.bat dlc\dlc008_french_tanks_unit_pack\ dlc008
call ZIP_DLCS_HELPER.bat dlc\dlc009_british_tanks_unit_pack\ dlc009
call ZIP_DLCS_HELPER.bat dlc\dlc010_us_tanks_unit_pack\ dlc010
call ZIP_DLCS_HELPER.bat dlc\dlc011_german_march_order_music_pack\ dlc011
call ZIP_DLCS_HELPER.bat dlc\dlc012_allied_radio_music_pack\ dlc012
call ZIP_DLCS_HELPER.bat dlc\dlc013_sabaton\ dlc013
call ZIP_DLCS_HELPER.bat dlc\dlc018_together_for_victory\ dlc018
call ZIP_DLCS_HELPER.bat dlc\dlc019_sabaton_vol2\ dlc019
call ZIP_DLCS_HELPER.bat dlc\dlc020_death_or_dishonor\ dlc020
call ZIP_DLCS_HELPER.bat dlc\dlc021_anniversary_pack\ dlc021
call ZIP_DLCS_HELPER.bat dlc\dlc022_waking_the_tiger\ dlc022